[package]
name = "steviegoodman/value-object"
description = "An encapsulation of a value for improving state management ergonomics in Lua."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml"
]

[dependencies]
Signal = "sleitnick/signal@2.0.1"